# Generated by Django 5.2 on 2025-04-26 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бармен',
                'verbose_name_plural': 'Бармены',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('bartender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='sheduler.bartender', verbose_name='Бармен')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DesiredTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('bartender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_time_off', to='sheduler.bartender', verbose_name='Бармен')),
            ],
            options={
                'verbose_name': 'Желаемый выходной',
                'verbose_name_plural': 'Желаемые выходные',
                'unique_together': {('bartender', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц')),
                ('shift_count', models.PositiveIntegerField(default=0, verbose_name='Количество смен')),
                ('bartender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_summaries', to='sheduler.bartender', verbose_name='Бармен')),
            ],
            options={
                'verbose_name': 'Итоги работы',
                'verbose_name_plural': 'Итоги работы',
                'unique_together': {('bartender', 'month')},
            },
        ),
    ]
